# Generated by Django 5.1.6 on 2025-06-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
